@startuml

class "automobil" as a{
  ime modela
  osnovna cijena
}

class "narudzba" as n{
  sifra narudzbe
  ukupna cijena
  rezervacija
}

class "stavka narudzbe" as sn{
  kolicina
  r1 racun
}

class "motor" as m{
  kod motora
  snaga u kw
  zakretni momenat
  broj ventila po cilindru
  emisije co2
  potrosnja
  gorivo
  cijena
}

class "ovijes" as sus{
    tip
    tvrdoca u nm
    cijena
}

class "naplatci" as kot{
    ime
    broj krakova
    proizvodjac guma
    cijena
}

class "prijenos" as p{
  kod mjenjaca
  tip
  broj brzina
  pogon
  cijena
}

class "interijer" as i{
  ime paketa
  materijal centralne konzole
  materijal detalja
  sjedala
  klimatizacija
  krov
  volan
  radio
  boja
  cijena
}

class "boja" as b{
  ime boje
  tip
  cijena
}

class "kupac" as k{
  ime
  prezime
  oib
}

class "firma" as f{
    naziv
    adresa
}


a "*" o-- "*" m
a "*" o-- "*" sus
sus "*" o-- "*" kot
b "1" -> "*" a
m "*" o-- "*" p
a "*" o- "1" i
n *- "1..*" sn
sn "*" o-- "1" a
k "1" --> "*" n
k "1" <-- "1" f

@enduml