<template>
  <v-container>
    <h1 align="center">Pregled narudžbe</h1><br>
    <v-divider></v-divider><br>
    <v-row>
      <v-col>
        <v-card
        class="mx-auto"
        max-width="500"
        variant="outlined">
          <v-card-title align="center">Automobil</v-card-title>
          <v-card-subtitle></v-card-subtitle>
          <v-card-subtitle></v-card-subtitle>
        </v-card>
      </v-col>
      <v-col>
        <v-card
        class="mx-auto"
        max-width="500"
        variant="outlined">
          <v-card-title align="center">Motor</v-card-title>
          <v-card-subtitle></v-card-subtitle>
          <v-card-subtitle></v-card-subtitle>
        </v-card>
      </v-col>
    </v-row>
    <v-row>
      <v-col>
        <v-card
        class="mx-auto"
        max-width="500"
        variant="outlined">
          <v-card-title align="center">Naplatci</v-card-title>
          <v-card-subtitle></v-card-subtitle>
          <v-card-subtitle></v-card-subtitle>
        </v-card>
      </v-col>
      <v-col>
        <v-card
        class="mx-auto"
        max-width="500"
        variant="outlined">
          <v-card-title>Interijer</v-card-title>
          <v-card-subtitle></v-card-subtitle>
          <v-card-subtitle></v-card-subtitle>
        </v-card>
      </v-col>
      <v-col>
        <v-card
        class="mx-auto"
        max-width="500"
        variant="outlined">
          <v-card-title>Boja</v-card-title>
          <v-card-subtitle></v-card-subtitle>
          <v-card-subtitle></v-card-subtitle>
        </v-card>
      </v-col>
    </v-row><br>
    <v-row>
      <v-col>
        <v-card-actions>
          <v-btn
          width="300"
          height="70"
          rounded
          outlined
          text
          color="green">
            Narudžba
          </v-btn>
        </v-card-actions>
      </v-col>
      <v-col>
        <v-card-actions>
          <v-btn
          width="300"
          height="70"
          rounded
          outlined
          text
          color="red">
            Poništavanje
          </v-btn>
        </v-card-actions>
      </v-col>
    </v-row> 
  </v-container>
</template>

<script>
export default {

}
</script>